apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: segundo-volume
          mountPath: /volume-dentro-do-container
    - name: jenkins-container
      image: jenkins/jenkins
      volumeMounts:
        - name: segundo-volume
          mountPath: /volume-dentro-do-container
  volumes:
    - name: segundo-volume
      hostPath:
        path: /home/segundo-volume
        type: DirectoryOrCreate
