apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-v1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: pv-disk
  storageClassName: standard
