apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort
  ports:
    - port: 80 # porta de acesso ao serviço
      # targetPort: 80 despachar na porta 80
      nodePort: 30001 
  selector:
    app: sistema-noticias